import ReportLogo from "../assets/document-logo.png";
import ImageOne from "../assets/WTR1-image-one.jpg"
import ImageTwo from "../assets/WTR1-image-two.jpg";
import ImageThree from "../assets/WTR1-image-three.jpeg";
import ImageFour from "../assets/WTR1-image-four.jpeg";
import ImageFive from "../assets/WTR1-image-five.jpeg";

export const ReportList = [
    {
        textName: "WTR_1",
        name: "Work Term Report F23",
        logo: ReportLogo,
        imageOne: ImageOne,
        imageTwo: ImageTwo,
        imageThree: ImageThree,
        imageFour: ImageFour,
        imageFive: ImageFive,
        descriptionOne: "Welcome to my website. This page is dedicated to my first co-op work term that I completed in Fall 2023. I worked as a Student IT Technician co-op at Computing and Communication Services at the University of Guelph. I was a part of the Client Productivity team at Managed Desktops in CCS. The office was in the basement of Johnston Hall at the University of Guelph. I hope you take away from this page the unique skills you can learn as an IT intern and how there are transferable skills that can be helpful for a software developer or software engineer to learn that will benefit them in their career.",
        descriptionTwo: "Computing and Communication Services is the central information technology (IT) department on campus that provides services and technology support to the university community. This includes Gryph Mail, University network connectivity, Microsoft Teams, logins and passwords, information security, file storage, databases, software, web hosting, web development and personal computing infrastructure support. The core values of CCS are Service Culture, Integrity, Individual Leadership, Teamwork, Agility and Communication. Several different divisions of CCS handle different tasks. I was a part of the Client Productivity division in the Managed Desktops team which provides services like Windows and MacOS support, application software installation, system rebuilds, network file and print services and support and hardware troubleshooting and diagnosis. CCS supports more than 5, 950 employee endpoint computers through Managed Desktops as well as 746 network switches and 3, 934 wireless access points across all University of Guelph locations. Additionally, of the 800 million emails received by the University in the 2021-2022 academic year, 95% were malicious and blocked by the Information Security team at CCS (University of Guelph, 63-64).",
        descriptionThree: "My main goals for this co-op work term were to improve my oral communication, problem-solving skills, and technological literacy. I tried to develop goals that related to my job tasks to improve my effectiveness as a technician. My first goal was to effectively communicate with clients both in person and on calls. Asking good questions to the client to understand the issue at hand to help me respond to clients with fixes sooner. and in the future with understanding the requirements for a software project or feature. My second goal was to improve on troubleshooting any issues with common tasks by building a knowledge base to rely on while problem-solving. This helped me on the job by allowing me to solve issues quicker, independently and without having to rely on other technicians. It will also help me in my next work experience by improving my independent problem-solving skills. My last goal was to understand key terminology and the key differences between technical synonyms. I wanted to learn to use technological terms properly in sentences when talking about them to other technicians. This allowed me to understand the technology required for the job and gain the skill of explaining technical concepts to other people with different backgrounds and levels of understanding when it comes to technology and software. This skill is very useful for jobs that require me to directly consult clients about software requirements as well as for pitching ideas about software features. I was able to complete all of the three primary goals that I had. I understood how to follow a general process to ask questions and inquire about a ticket that properly informs me about the context of the problem. I improved how I troubleshot common issues like decommissions and application installs and contributed to documenting the standard operating procedure of computer builds by providing a list of several potential solutions to common problems that occur during the build process that I have experienced. I learned about IT technology terms and I can simplify technical concepts for clients when explaining the reasoning behind the issues they face as well as the rationale behind the solution to help them prevent the same issue from occurring in the future. I can efficiently use technologies like Microsoft Endpoint Configuration Manager and Active Directory to resolve issues as well as IT issue tracking software like FootPrints to document and keep track of tickets.",
        descriptionFour: "At this job, I worked closely with other technicians, analysts and co-op students to resolve tickets that were assigned to me on FootPrints. They ranged from common tasks like decommissioning computers, completing a build or rebuild of a computer, application installs, and delivering and setting up computers and monitors to issues with monitor screens or docking stations not working properly, Outlook or Adobe Acrobat settings issues, and replacing malfunctioning hardware components of laptops like fans. In many cases, I had to troubleshoot or resolve issues with processes that we follow for common tasks. I documented solutions that I found for these issues. I needed critical-thinking skills, communication skills, and the ability to use tools like Microsoft Endpoint Configuration Manager, Active Directory, and FootPrints to do my job effectively. I learned a majority of these skills during onboarding and throughout my co-op term.",
        descriptionFive: "Overall, I had lots of fun learning about how different technologies and systems work in an IT environment. I improved my communication, technological literacy, and problem-solving skills, which are all beneficial to my career in the software industry.",
        descriptionSix: "I want to acknowledge my manager, Brian Thomson, and the technical analyst and supervisor for my co-op term, Haniya Saleh, for their incredible work at CCS and for teaching me about how CCS works. I wanted to thank Joey Aversa, Theron Simon, Stefan Romanescu, Jeff Hamilton, James McGarry, and Jill Hogg for all of their advice and help when I worked on tickets. I also want to acknowledge the three other co-op students that I worked with throughout my co-op term: Krishna Suthanthireswaran, Nuno Simoes, and Jonathon Kocevar. It was fun talking to and working alongside them.",
        sourceOneTitle: "Fact Book 2021-2022.",
        sourceOnePublisher: "University of Guelph, 2022,", 
        sourceOneWebTitle: "Institutional Research and Planning - University of Guelph,",
        sourceOneUrl: "https://irp.uoguelph.ca/system/files/UofG-Fact-Book-2021-2022_DigiAccess.pdf" ,
        sourceOneDate: ", Accessed 11 Jan. 2024.",
        sourceTwoTitle: "Johnston Hall.",
        sourceTwoPublishDate:"2021.", 
        sourceTwoPublisher: "University of Guelph,",
        sourceTwoUrl: "https://www.uoguelph.ca/maps/locations/johnston-hall",
        sourceTwoDate: ". Accessed 11 Jan. 2024.",
    },
]